version: '3'

volumes:
  pg_data_taski:
  static_volume_taski:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data_taski:/var/lib/postgresql/data

  backend:
    image: mordovind/taski_backend
    env_file: .env
    volumes:
      - static_volume_taski:/backend_static
    depends_on:
      - db
    user: "0:0"

  frontend:
    image: mordovind/taski_frontend
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static_volume_taski:/frontend_static

  gateway:
    image: mordovind/taski_gateway
    env_file: .env
    volumes:
      - static_volume_taski:/staticfiles/
    ports:
      - 8000:80
    depends_on:
      - backend

networks:
  taski_network:
    driver: bridge
